language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_script:
  - dotnet restore
  - cd Pug.Clients.Web
  - npm install
  - npm install -g gulp-cli
  - cd ../
script:

  - cd Pug.Clients.Web
  - gulp build-dev
  - cd ../
